# Generated by Django 4.2 on 2024-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveBigIntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('field_of_study', models.CharField(max_length=50)),
                ('grade', models.FloatField()),
                ('chinese_score', models.PositiveIntegerField()),
                ('math_score', models.PositiveIntegerField()),
                ('english_score', models.PositiveIntegerField()),
            ],
        ),
    ]
